### ISSUE TITLE
Is it possible to select more than 1 value in a checkbox?

### ISSUE THREAD

**Issue by laresbernardo** [pridiltal/staplr#21]
Hello.
I tried with `fields$field$value <- c(1,3)` but doesn't work. Is there a way to check more than one option in a field with multiple checkboxes?
Thanks!

**Comment by oganm** [comment]
Do you see a field name like `fields$field_2`. I am trying to experiment with creating checkbox groups but that is what shows up then I try to create one like a radio button group. Otherwise all boxes should have independent names. This is another case the file could be useful.

**Comment by laresbernardo** [comment]
No, there are no `fields$field_2` features in this case. I am forced to select 1 of my 8 options, but it doesn't let me select more than one. There must be a way, right?

**Comment by oganm** [comment]
Can you select multiple options when you try to fill it by hand? If not, that input type only accepts a single entry.

If you can select multiple inputs, there probably is a way to do this through pdftk but since I have never seen a file like that, currently staplr isn't built to handle that case. I need an example file so I can see how pdftk handles it so I can implement it.

I am playing with my example file but so far I couldn't find how to create multiple checkboxes that are represented by a single field. So if you sent the file you are working on or something that has the same features, I could fix the issue

**Comment by laresbernardo** [comment]
That would be awesome @oganm 
Actually, I have just checked in my file and, in this particular case, I can't select more than one input. But, nonetheless, it would be great to select more than one option with a simple numeric vector for future cases like this!
Thanks again

**Comment by oganm** [comment]
You might have to take that up to Adobe. That input type is designed to allow only one selection. If the creator of the file grouped those together, that means they either don't expect you to pick multiple options or they made a mistake.

If you have means to edit the pdf, you have to break that group apart into individual inputs (don't quite know how to do that myself though. probably something adobe acrobat can handle)
