### ISSUE TITLE
files with dots in field names cannot be processed

### ISSUE THREAD

**Issue by pabloboswell** [pridiltal/staplr#24]
I have loaded a sample PDF that is already filled in, and using get_fields produces the full list of fields.  However, when I use set_fields to create a copy of the filled PDF, certain fields are blank, and some values have been written to the wrong field.

**Comment by oganm** [comment]
Could you send me the pdf and tell me which fields you tried to fil? Are the fields with same names?

**Comment by pabloboswell** [comment]
So, the template with example values is "CMS-1500 sample.pdf" and I am
copying these values from get_fields to "CMS-1500 Filled.pdf" using
set_fields.  For example,  lsPDFSampleFields$`1a`$value = "PM-00012345",
but in the new PDF, the field is blank, and the value has been written to
lsPDFSampleFields$`diag21.1a`$value.

Here is my code:

*library(staplr)*


*##establish file paths*
*usrPDFSamplePath <- "C:/Users/pboswell/Downloads/CMS-1500 sample.pdf"*
*usrPDFBlankPath <- "C:/Users/pboswell/Downloads/CMS-1500 blank.pdf"*

*##get sample fields*
*lsPDFSampleFields <- get_fields(usrPDFSamplePath)*

*##copy sample fields*
*lsPDFFilledFields <- lsPDFSampleFields*

*set_fields(usrPDFBlankPath,usrPDFFilledPath,lsPDFFilledFields)*


Now that I think it through, it must have to do with you fdfEdit function
and the regex expressions you use to replace values (because the field
names have "." in them)


*Pablo Boswell*
PabloBoswell@gmail.com
(505) 250-3118

**Comment by oganm** [comment]
It is better for me to have the actual file you are using as files that look the same might be encoded differently. ~Do you mean [this](https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/Downloads/CMS1500.pdf) file?~ Actually it can't be that file because that one is not a form so it would help me if you sent your version.

"."s could really be the problem. I probably should be doing exact matching there

**Comment by pabloboswell** [comment]
Yes, that sample file is fine.


Thank you,
*Pablo Boswell*
PabloBoswell@gmail.com
(505) 250-3118

**Comment by oganm** [comment]
No that file is not useful because it is not a fillable form. That's why I was asking for whatever you had in hand. I could test by making my own test file with similarly named fields too but it's better to test with the file that has the issue in case that is not the real problem or if there are other issues.

If you were trying to attach the file to your mail. I am afraid it's not making it in here

**Comment by pabloboswell** [comment]
OK, sorry I thought I had attached.  Should be attached now.  So, would
another option be to create my own formed version?  Can I choose the
metadata names myself?



*Pablo Boswell*
PabloBoswell@gmail.com
(505) 250-3118

**Comment by oganm** [comment]
I meant files attached in mails do not arrive to github. You need to either attach directly on this page or mail directly to [me](mailto:ogan.mancarci@gmail.com).

I did replicate the issue (I think) with a test file of my own right now and it doesn't seem to be a regex issue but the .'s in the names causing pdftk act weirdly when generating the FDF file (intermediate text file that is filled as an input for pdftk before filling the form). It was wierder than I anticipated so your file could still help me to see if what I did is the same kind of weird.

**Comment by oganm** [comment]
[This](https://forums.adobe.com/thread/1923197) is somewhat related to the issue. When there are dots in the field names, there seems to be some assumption of hierarchy

**Comment by pabloboswell** [comment]
That makes sense.  I simply went in and removed the dots for all form field
names, and everything works perfectly!  I think this ended up being the
fastest solution since we only need the one document template.


Thank you for your responsiveness!
*Pablo Boswell*
PabloBoswell@gmail.com
(505) 250-3118

**Comment by oganm** [comment]
No problem. Not closing this since I still want to see if I can deal with it

**Comment by oganm** [comment]
The latest fix actually introduces more problems as it is very aggressive about removal of hierarchies. might have to write a full parser to make this right or use something to turn fdf into xfdf. using `rly` is an option but I don't quite know how to use it yet. if anyone want to instruct me on how to write parsers I would welcome the help.

the latest push replaces the warning with an error till I find a real solution.

**Comment by pabloboswell** [comment]
My guess is that the document hierarchies were incorrectly generated, so it
may be more hassle than it's worth to find a solution.

*Pablo Boswell*
PabloBoswell@gmail.com
(505) 250-3118

**Comment by oganm** [comment]
In you case, you didn't need the hierarchies and weren't thinking about them when you named your fields. However there are other files in the wild that intentionally or unintentionally includes these hierarchical structures. since not all users have control over their field names, and others might want to keep the hierarchical structures, the ideal solution would be to have a way of filling them correctly

for now the temporary solution is to return an error in such files since I don't have any more time to work on this now but I still want to solve this at some point in the preferably near future.

sorry if you're still getting mails from this issue by the way. you should be able to unsubscribe from it if you don't want to follow the issue.
