### ISSUE TITLE
Cran removal 

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#62]
@pridiltal, seems like the package was removed from cran, likely because of the Java version issue. The current version should be fine. Mind submitting it?

**Comment by oganm** [comment]
@pridiltal reminder poke

**Comment by eliaswestonfarber** [comment]
@pridiltal if this could get back on cran that would be awesome!

**Comment by eliaswestonfarber** [comment]
@oganm are you able to release a new version? 

because this is what I found about getting a package back on cran...

Getting a package back on CRAN (Comprehensive R Archive Network) after it was removed requires correcting the issues that led to its removal and resubmitting it. Here's a step-by-step guide:

Find out why it was removed: Check the CRAN Archive page and your email to understand the reasons for the package's removal. The reasons could range from failing to pass checks, failing to respond to the CRAN team's queries, or serious bugs.

Fix the issues: Once you've determined the reasons for the package's removal, take the necessary steps to correct those issues. This could involve fixing bugs, updating the package's documentation, responding to the CRAN team's queries, or ensuring your package passes all necessary checks.

Update Version Number: Increase the version number of your package. This helps to differentiate the updated package from the older, removed version.

Run checks: Before resubmitting, run R CMD check --as-cran on your package. This will help ensure that your package meets all of CRAN's current policies and guidelines. Fix any errors, warnings, or notes that appear.

Resubmit the package: If the issues that led to the removal have been resolved and the package passes all checks, it can be resubmitted to CRAN. Use the devtools::release() function, or submit manually through the CRAN submission form.

Follow up: After resubmitting the package, it's essential to monitor your email for any responses from the CRAN team. If any further issues are raised, be sure to address them promptly.

Remember, it is important to maintain communication with the CRAN team throughout this process. They are there to help ensure that your package meets the high standards necessary for inclusion in the CRAN repository. They are generally responsive to queries and can provide advice on resolving any problems that may arise.

**Comment by oganm** [comment]
Hi, I was waiting to hear back from @pridiltal but just sent CRAN a mail about continuing with the resubmission.

**Comment by eliaswestonfarber** [comment]
What about the point that we may need the version of the package to be updated for the resubmit?

**Comment by oganm** [comment]
That is already done with the last push. But it seems like CRAN is having problems with package submission as of today so neither I nor @pridiltal will be able to go on with it until they fix it on their end.

> Dear developers,
> 
> CRAN submissions are currently partly not possible due to some
> infrastructure issues. Please so NOT contact us if you see "Unpacking
> failed. Please make sure the tar.gz was created with R CMD build. [...]".
> 
> In addition, processing the CRAN incoming queue of packages (CRAN
> pretest) is currently delayed by 2 days.
> 
> Both issues are known and CRAN sysadmins will work on the issues

**Comment by oganm** [comment]
oh nevermind.. i lied about version change. doing it now

**Comment by eliaswestonfarber** [comment]
thanks!

**Comment by eliaswestonfarber** [comment]
Hey does cran look at HEAD on the repo or the named releases https://github.com/pridiltal/staplr/releases because if they look at releases this should have a 3.1.2 in it (which it currently doesn't)

**Comment by oganm** [comment]
Nope. CRAN doesn't look at github at all. Only version in the DESCRIPTION matters

**Comment by eliaswestonfarber** [comment]
Any word from CRAN?

**Comment by oganm** [comment]
The submission was successful this time but it requires approval from the maintainer. have mailed cran about what to do if we don't get a response.

**Comment by oganm** [comment]
Looks like the only way to bring it back without the current maintainer's approval is to change maintainers, which is possible, but considering it's the middle of summer (well not in australia but still.. don't know when academics of different localities tend to disappear) I'd prefer to wait a bit longer before making that change since the package is readily available on github.

**Comment by oganm** [comment]
CRAN feedback

- [x] Currently it reads: "Provides function to ...", Probably it should be: "Provides functions to ..."
- [x] always write package names, software names and API (application programming interface) names in single quotes in title and description. e.g: --> 'Java 8'
- [x] \value to .Rd files regarding exported 
- [x] Java specification is not in standardized form. (i was sure i fixed this...)
- [x] \dontrun{} should only be used if the example really cannot be executed
- [x] The ownership of copyright and intellectual property rights of all components of the package must be clear and unambiguous. (a bit unsure about what exactly is needed for this. Possibly copyright information for pdftk-java?)

**Comment by oganm** [comment]
Additional changes
- fixed return fields in other functions
- Removal of all dontrun sections when running during tests are undesirable. The donttest suggestion appears to have a spotty history https://github.com/r-lib/devtools/issues/2216

**Comment by oganm** [comment]
Been rereading https://cran.r-project.org/doc/manuals/R-exts and pretty sure java specification is right. I can only assume the reviewer meant the mention of java in description instead which is now removed

**Comment by eliaswestonfarber** [comment]
Any updates?

**Comment by oganm** [comment]
Only need to deal with the crediting issues then resubmit. Sorry for the delay, just been a bit busy. have any issues accessing the package in the meanwhile?

**Comment by oganm** [comment]
@pridiltal The package should be ready for resubmission

**Comment by eliaswestonfarber** [comment]
I mean I can install via github but its concerning, this package is the only package I am installing this way, and it seems like it should be on cran so thats why I am checking in on this. Has @pridiltal been responsive to you since you opened this thread in May? Does @pridiltal need to do anything or can you go to cran directly?

**Comment by oganm** [comment]
Yep we did talk. The latest delay was on me on addressing the submission comments. I have resubmitted to CRAN just now. Hopefully it won't return again

**Comment by nzgwynn** [comment]
When I run 

`install.packages("staplr")` 

the package installs from CRAN, but I get this error when I run

`> library(staplr)
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
 `
Any suggestions? I'm on R 4.3.1 in the newest RStudio instance

**Comment by nzgwynn** [comment]
I downloaded Java from the website, restarted both R and RStudio and the package still can't find it.

**Comment by oganm** [comment]
Staplr uses rjava to find your Java installation. Their page offers a few hints in troubleshooting

https://github.com/s-u/rJava

I will close this issue for now since the topic of the issue is resolved now but if you are unable fix it by taking a look at rjava page feel free to open a new one
