### ISSUE TITLE
Field names with apostrophes do not show up in fields with get_fields()

### ISSUE THREAD

**Issue by cookm346** [pridiltal/staplr#63]
If a field name has an apostrophe (e.g., "Employee's birthday") the field will simply not show up when you use get_fields().

**Comment by oganm** [comment]
I generated one such file with one "Employee's birthday" and "Employee’s birthday" both were fillable albeit the ’ character is slightly more involved  and should have given you a warning when you tried. See the example file below

[issueTest.pdf](https://github.com/pridiltal/staplr/files/12490447/issueTest.pdf)

Using this one can either do

```r

fields = get_fields('issueTest.pdf')
fields$`Employee's birthday`$value = 'today'
fields$`Employee#E2#80#99s birthday`$value = 'tomorrow'
set_fields('issueTest.pdf',output_filepath = 'tested.pdf',fields = fields)
```

or 

```r
fields = get_fields('issueTest.pdf',convert_field_names = TRUE)
fields$`Employee's birthday`$value = 'today'
fields$`Employee’s birthday`$value = 'tomorrow'
set_fields('issueTest.pdf',output_filepath = 'tested.pdf',fields = fields,convert_field_names = TRUE)
```

Due to the way pdfs encode the ’, the default way of reading will have a less than readable name. You can fix this by using `convert_field_names`

**Comment by cookm346** [comment]
Thank you for your example, that makes sense and solves the issue.
